### ISSUE TITLE
Photos: instruct users to upload square photos or automatically crop or pad them

### ISSUE THREAD

**Issue by fallax** [AndreaUnlimited/starfriends#19] opened 2016-02-27 13:19 UTC
Currently people are uploading rectangular photos, which get squished down to a 310x310 square when they get displayed on the page.

I'm guessing the thumbnailing is being done by ImageMagick - if so there are some nice options to add padding around the edges of an image to make it fit into a square thumbnail. Ask me about this if you need to know more.

Regardless of whether that gets done or not, we could probably encourage better quality profile pictures by recommending that people upload square pictures rather than rectangular ones.

**Comment by fallax** [comment] 2016-02-27 13:20
See for example http://starfriends.org/index.php?profile=41

**Comment by Cassolotl** [comment] 2016-02-27 13:23
> Regardless of whether that gets done or not, we could probably encourage better quality profile pictures by recommending that people upload square pictures rather than rectangular ones.

This is already a thing. But if it's not clear enough, perhaps it should be made clearer?

![screen shot 2016-02-27 at 13 23 00](https://cloud.githubusercontent.com/assets/6607512/13373082/4b31026c-dd55-11e5-98d6-3d1dd9447472.png)

**Comment by fallax** [comment] 2016-02-27 13:41
Yeah, that's really not obvious enough at the moment, and there's nothing that rejects photos or fixes them if someone doesn't follow the instructions.

**Comment by fallerOfFalls** [comment] 2016-02-27 14:01
duplicate of #16

**Closed as completed by fallerOfFalls** 2016-02-27 14:01 UTC
Labels: duplicate
